version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
    working_directory: /go/src/github.com/heroku/libhkbuildpack
    environment:
      GO111MODULE=on
    steps:
      - checkout
      - run: make test

